spring.application.name=service-registry
server.port=8761
eureka.instance.hostname=service-registry-9t8c.onrender.com
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.server.enable-self-preservation=false
eureka.client.allow-remote-clients=true