# FROM openjdk:21
# WORKDIR /app
# RUN chmod +x mvnw
# COPY . .
# RUN ./mvnw clean package -DskipTests
# EXPOSE 8081
# ENTRYPOINT ["java", "-jar", "target/apiGateway-0.0.1-SNAPSHOT.jar"]


FROM maven:3.8.6-openjdk-21 AS build
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

FROM openjdk:21
WORKDIR /app
COPY --from=build /app/target/apiGateway-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 8081
ENTRYPOINT ["java", "-jar", "app.jar"]
