# FROM openjdk:21
# WORKDIR /app
# RUN chmod +x mvnw
# COPY . .
# RUN ./mvnw clean package -DskipTests
# EXPOSE 8084
# ENTRYPOINT ["java", "-jar", "target/processingService-0.0.1-SNAPSHOT.jar"]


FROM maven:3.9.6-eclipse-temurin-21 AS build
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

FROM openjdk:21
WORKDIR /app
COPY --from=build /app/target/processingService-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 8084
ENTRYPOINT ["java", "-jar", "app.jar"]