spring.application.name=apiGateway
server.port=8081



#spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/InterviewTrainer
#spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/InterviewTrainer/protocol/openid-connect/certs

#keycloak.auth-server-url=http://localhost:8080
#keycloak.realm=InterviewTrainer
#keycloak.resource=interview-trainer-client
#keycloak.public-client=true
#keycloak.bearer-only=true
spring.main.web-application-type=reactive
spring.cloud.gateway.discovery.locator.enabled=true

#spring.cloud.gateway.routes[0].id=auth-service
#spring.cloud.gateway.routes[0].uri=lb://authService
#spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/auth/**
logging.level.com.authentication=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
#application.cors.origins=http://localhost:3000,http://localhost:3001
#spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedOrigins=http://localhost:3000
#spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedMethods=GET
#spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedHeaders=*
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration



#spring.cloud.gateway.routes[1].id=user-service
#spring.cloud.gateway.routes[1].uri=lb://userService
#spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/user/**
#spring.cloud.gateway.routes[1].filters[0]=JwtAuthenticationFilter
#
#spring.cloud.gateway.routes[2].id=interviewSession-service
#spring.cloud.gateway.routes[2].uri=lb://interviewSessionService
#spring.cloud.gateway.routes[2].predicates[0]=Path=/api/v1/interview/**
#spring.cloud.gateway.routes[2].filters[0]=JwtAuthenticationFilter
#
#spring.cloud.gateway.routes[3].id=notification-service
#spring.cloud.gateway.routes[3].uri=lb://notificationService
#spring.cloud.gateway.routes[3].predicates[0]=Path=/api/v1/notification/**
#spring.cloud.gateway.routes[3].filters[0]=JwtAuthenticationFilter
#
#spring.cloud.gateway.routes[4].id=processing-service
#spring.cloud.gateway.routes[4].uri=lb://processingService
#spring.cloud.gateway.routes[4].predicates[0]=Path=/api/v1/processing/**
#spring.cloud.gateway.routes[4].filters[0]=JwtAuthenticationFilter
#
#spring.cloud.gateway.routes[5].id=question-service
#spring.cloud.gateway.routes[5].uri=lb://questionGenerationService
#spring.cloud.gateway.routes[5].predicates[0]=Path=/api/v1/question/**
#spring.cloud.gateway.routes[5].filters[0]=JwtAuthenticationFilter
#
#spring.cloud.gateway.routes[6].id=storage-service
#spring.cloud.gateway.routes[6].uri=lb://storageService
#spring.cloud.gateway.routes[6].predicates[0]=Path=/api/v1/storage/**
#spring.cloud.gateway.routes[6].filters[0]=JwtAuthenticationFilter
#
#spring.cloud.gateway.routes[7].id=feedbackAndScoring-service
#spring.cloud.gateway.routes[7].uri=lb://feedbackAndScoringService
#spring.cloud.gateway.routes[7].predicates[0]=Path=/api/v1/feedback/**
#spring.cloud.gateway.routes[7].filters[0]=JwtAuthenticationFilter
