spring.application.name=${SPRING_APPLICATION_NAME}
server.port=${SERVER_PORT}

logging.level.com.authentication=${LOGGING_LEVEL_COM_AUTHENTICATION}
logging.level.org.springframework.security=${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY}
logging.level.org.springframework.web=${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB}

spring.autoconfigure.exclude=${SPRING_AUTOCONFIGURE_EXCLUDE}

spring.cloud.gateway.discovery.locator.enabled=${SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_ENABLED}



