spring.application.name=userService

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PWD}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
maven-compiler-plugin.version=3.13.0
logging.level.com.authentication=DEBUG
logging.level.org.springframework.security=DEBUG


#keycloak.auth-server-url=http://localhost:8080
#keycloak.realm=InterviewTrainer
#keycloak.resource=interview-trainer-client
#keycloak.public-client=true
#keycloak.bearer-only=true
# Prevent immediate shutdown
spring.main.allow-circular-references=true
eureka.client.registerWithEureka=true
eureka.client.fetchRegistry=true
server.port=8085
cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api_key=${CLOUDINARY_API_KEY}
cloudinary.api_secret=${CLOUDINARY_API_SECRET}
spring.redis.host=${REDIS_HOST}
spring.redis.port=6379
spring.cache.type=redis
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.datatype.jsr310.serializer.write-dates-as-timestamps=false
spring.jpa.open-in-view=false

spring.jackson.serialization.fail-on-empty-beans=false

