FROM openjdk:21
WORKDIR /app

# Copy all files
COPY . .

# Ensure mvnw has execute permission
RUN chmod +x mvnw

# Build the project
RUN ./mvnw clean package -DskipTests

# Expose port
EXPOSE 8761

# Run the application
ENTRYPOINT ["java", "-jar", "target/service-registry-0.0.1-SNAPSHOT.jar"]
