spring.application.name=authService
server.port=8088
logging.level.com.authentication=DEBUG
logging.level.org.springframework.security=DEBUG
cloudinary.cloud_name=dbzebdg6r
cloudinary.api_key=548182199714912
cloudinary.api_secret=20gVwnC8TvDvCk7qwxKpK6_gfKY
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB