# FROM openjdk:21
# WORKDIR /app
# RUN chmod +x mvnw
# COPY . .
# RUN ./mvnw clean package -DskipTests
# EXPOSE 8081
# ENTRYPOINT ["java", "-jar", "target/notificationService.jar"]

FROM maven:3.9.6-eclipse-temurin-21 AS build
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

FROM openjdk:21
WORKDIR /app
COPY --from=build /app/target/notificationService.jar app.jar
EXPOSE 8081
ENTRYPOINT ["java", "-jar", "app.jar"]