spring.application.name=interviewSessionService
server.port=8090

spring.datasource.url=${DB_URL:jdbc:postgresql://postgres.cb0y8yyigogt.eu-north-1.rds.amazonaws.com:5432/interview-trainer}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PWD:postgres123}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
livekit.apiKey=APIuRYjqXMnbM52
livekit.apiSecret=foM9oqwKvvnzYPqjPCeepfD4Cy6CyYeqZ3fjAXCent5X
logging.level.org.springframework.messaging=DEBUG
logging.level.org.springframework.web.socket=DEBUG
logging.level.com.authentication=DEBUG
logging.level.org.springframework.security=DEBUG
spring.mail.username=codeetgo@gmail.com
spring.mail.password=drtp ioud cknl yrll
spring.redis.host=redis-4di0fg.serverless.eun1.cache.amazonaws.com:6379
spring.redis.port=6379
spring.cache.type=redis
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.datatype.jsr310.serializer.write-dates-as-timestamps=false